Update open-vscode-remote script

diff --git a/bin/open-vscode-remote b/bin/open-vscode-remote
--- a/bin/open-vscode-remote
+++ b/bin/open-vscode-remote
@@ -1,10 +1,22 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
+dev_desktop_hostname="dev"
 workspace_root="/workplace/$USER"
+workspaces=$(ssh -t $dev_desktop_hostname "ls $workspace_root | tr '\n' ' '" 2> /dev/null)
+if [[ $? -ne 0 ]]; then
+    echo "Error retrieving DevDesktop version sets; try running mwinit"
+    exit 1
+fi
+
+if [ ! -z "$1" ]; then
+    echo "Scoping to matches with '$1'..."
+    workspaces=$(echo $workspaces | tr ' ' '\n' | grep -i $1 | tr '\n' ' ')
+fi
+
 PS3="Select a Brazil workspace: "
-select dir in $(ssh -t dev "ls $workspace_root | tr '\n' ' '" 2> /dev/null); do
+select dir in $workspaces; do
     full_path="$workspace_root/$dir"
     echo "Opening $full_path in VSCode remote..."
-    code --remote ssh-remote+dev $full_path
+    code --remote ssh-remote+$dev_desktop_hostname $full_path
     break
 done
